services:
  - type: web
    name: jukebox-tempo-v2
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_BASE_PATH
        value: /
      - key: PORT
        value: 10000
      - key: VITE_YOUTUBE_API_KEY
        sync: false
  
  # Separate static site configuration for serving static assets with headers
  - type: web
    name: jukebox-tempo-v2-static
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
